$linkedData:
  term: ProductDimensions
  '@id': https://schema.org/Product
title: Product Dimensions
description: Confirmed dimensions, as applicable to the product type (for example diameter or thickness).
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - ProductDimensions
    default:
      - ProductDimensions
    items:
      type: string
      enum:
        - ProductDimensions
  length:
    title: Length
    description: Product length.
    $ref: ./MeasuredValue.yml
    $linkedData:
      term: length
      '@id': https://schema.org/length
  width:
    title: Width
    description: Product width.
    $ref: ./MeasuredValue.yml
    $linkedData:
      term: width
      '@id': https://schema.org/width
  thickness:
    title: Thickness
    description: Product thickness.
    $ref: ./MeasuredValue.yml
    $linkedData:
      term: thickness
      '@id': https://schema.org/height
  diameter:
    title: Diameter
    description: Product diameter.
    $ref: ./MeasuredValue.yml
    $linkedData:
      term: diameter
      '@id': https://schema.org/diameter
additionalProperties: false
required:
  - type
example: |-
  {
    "type": ["ProductDimensions"],
    "length":   {
      "type": ["MeasuredValue"],
      "value": "6000",
      "unitCode": "MM"
    },
    "width": {
      "type": ["MeasuredValue"],
      "value": "6000",
      "unitCode": "MM"
    },
    "thickness": {
      "type": ["MeasuredValue"],
      "value": "6000",
      "unitCode": "MM"
    }
  }