$linkedData:
  term: Workflow
  '@id': http://www.omg.org/spec/BPMN/2.0.2#BusinessProcess
title: Workflow
description: This is a property of a TraceablePresentation, and receives its semantics from that RDF Class.
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - Workflow
    default:
      - Workflow
    items:
      type: string
      enum:
        - Workflow
  definition: 
    description: The Workflow Definition indicates the intention behind the presentation. 
    type: array
    items:
      type: string
    $linkedData:
      term: definition
      '@id': http://www.omg.org/spec/BPMN/2.0.2#Definition
  instance:
    description: The Workflow Instance identifies this particular workflow. Subsequent presentations may indicate correlation by referencing the same instance identifier.
    type: array
    items:
      type: string
    $linkedData:
      term: instance
      '@id': http://www.omg.org/spec/BPMN/2.0.2#Instance
additionalProperties: false  
required:
  - type
example: |-
  {
    "type": [
      "Workflow"
    ],
    "definition": [
      "https://w3id.org/traceability/#us-cbp-entry"
    ],
    "instance": [
      "urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
    ]
  }