$linkedData:
  term: CTPATEIPApplicationCredential
  '@id': https://w3id.org/traceability#CTPATEIPApplicationCredential
title: CTPAT Ecommerce Incentive Program Application Credential
tags:
  - eCommerce
description: >-
    Credential used by Ecommerce participants to register for US CBP CTPAT Ecommerce Incentive Program Certification.
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - CTPATEIPApplicationCredential
    default:
      - VerifiableCredential
      - CTPATEIPApplicationCredential
    items:
      type: string
      enum:
        - VerifiableCredential
        - CTPATEIPApplicationCredential
  id:
    type: string
  name:
    type: string
  description:
    type: string
  issuanceDate:
    type: string
  issuer:
    $ref: ../common/Organization.yml
  credentialSubject:
    $ref: ../common/CTPATEIPApplication.yml
  proof:
    type: object
additionalProperties: false
required:
  - '@context'
  - type
  - issuanceDate
  - issuer
  - credentialSubject
example: |-
  {
    "type": [
      "VerifiableCredential",
      "CTPATEIPFulfillmentCredential"
    ],
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "did:key:z6LSpdSReUHCjYcQb1243aF1vS7sd9ArK585Mm4ktARQxatd",
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "name": "US CBP Ecommerce Certification Office"
    },
    "issuanceDate": "2022-01-13T09:16:46Z",
    "credentialSubject": {
      "type": [
        "CTPATEIPApplication"
      ],
      "applicantOrganization": {
        "type": [
          "Organization"
        ],
        "id": "did:web:ecommerce-fulfillment.example.com",
        "name": "Fulfillment Global, Ltd."
      },
      "applicantType": "Fulfillment"
    },
    "proof": {
      "type": "Ed25519Signature2018",
      "created": "2022-11-25T13:44:58Z",
      "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "proofPurpose": "assertionMethod",
      "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..v9QUV2i8FYOyUcSi-Sk2JNtpC9lZSjwz16WK3RmOfIRaMXidxWXRTqXR5BnptCYvBVnmnof0D3EJ_X5rhThMCw"
    }
  }