name: CD

on:
  push:
    branches:
      - test_branch

jobs:
  release-unstable:
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:all

      - name: Test Schemas
        run: npm run test:schemas

      - name: Test Credentials
        run: npm run test:credentials

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup assets
        run: |
          mkdir -p ./versions/${{ steps.version-bump.outputs.newTag }}
          cp ./docs ./versions/${{ steps.version-bump.outputs.newTag }}

      - name: Deploy test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./docs

      - name: Create new Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.version-bump.outputs.newTag }}
          files: |
            LICENSE.md
            ./docs
