name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Jest
        run: cd packages/traceability-schemas && npm run test
